// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Viamatica.Infrastructure.Data;

#nullable disable

namespace Viamatica.Infrastructure.Migrations
{
    [DbContext(typeof(ViamaticaDbContext))]
    [Migration("20250101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            ViamaticaDbContextModelSnapshot.BuildModelSnapshot(modelBuilder);
        }
    }
}
