// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viamatica.Infrastructure.Data;

#nullable disable

namespace Viamatica.Infrastructure.Migrations
{
    [DbContext(typeof(ViamaticaDbContext))]
    partial class ViamaticaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Viamatica.Domain.Entities.Attention", b =>
                {
                    b.Property<int>("AttentionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attentionid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttentionId"));

                    b.Property<string>("AttentionTypeId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("attentiontype_attentiontypeid");

                    b.Property<int>("CashierUserId")
                        .HasColumnType("int")
                        .HasColumnName("cashier_userid");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_clientid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completedat");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_contractid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdat");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notes");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("attentionstatus_statusid");

                    b.Property<int>("TurnId")
                        .HasColumnType("int")
                        .HasColumnName("turn_turnid");

                    b.HasKey("AttentionId");

                    b.HasIndex("AttentionTypeId");

                    b.HasIndex("CashierUserId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TurnId");

                    b.ToTable("attention", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("statusid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.HasKey("StatusId");

                    b.ToTable("attentionstatus", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionType", b =>
                {
                    b.Property<string>("AttentionTypeId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("attentiontypeid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.HasKey("AttentionTypeId");

                    b.ToTable("attentiontype", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Cash", b =>
                {
                    b.Property<int>("CashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cashid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CashId"));

                    b.Property<string>("Active")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("active");

                    b.Property<string>("CashDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cashdescription");

                    b.HasKey("CashId");

                    b.ToTable("cash", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.CashSession", b =>
                {
                    b.Property<int>("CashSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cashsessionid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CashSessionId"));

                    b.Property<int>("CashId")
                        .HasColumnType("int")
                        .HasColumnName("cash_cashid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("endedat");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("startedat");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_userid");

                    b.HasKey("CashSessionId");

                    b.HasIndex("CashId")
                        .IsUnique()
                        .HasFilter("[endedat] IS NULL");

                    b.HasIndex("UserId");

                    b.ToTable("cashsession", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clientid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deletedat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("identification");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("ReferenceAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referenceaddress");

                    b.HasKey("ClientId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[isdeleted] = 0");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasFilter("[isdeleted] = 0");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contractid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_clientid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deletedat");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("enddate");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<int>("MethodPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("methodpayment_methodpaymentid");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_serviceid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("startdate");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("statuscontract_statusid");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MethodPaymentId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StatusId");

                    b.ToTable("contract", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("deviceid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("devicename");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_serviceid");

                    b.HasKey("DeviceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.MethodPayment", b =>
                {
                    b.Property<int>("MethodPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("methodpaymentid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodPaymentId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.HasKey("MethodPaymentId");

                    b.ToTable("methodpayment", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.NavigationMenu", b =>
                {
                    b.Property<int>("NavigationMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("navigationmenuid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NavigationMenuId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("displayorder");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("label");

                    b.Property<string>("MenuKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("menukey");

                    b.Property<int?>("ParentNavigationMenuId")
                        .HasColumnType("int")
                        .HasColumnName("parentnavigationmenuid");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("route");

                    b.HasKey("NavigationMenuId");

                    b.HasIndex("MenuKey")
                        .IsUnique();

                    b.HasIndex("ParentNavigationMenuId");

                    b.ToTable("navigationmenu", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.NavigationMenuRole", b =>
                {
                    b.Property<int>("NavigationMenuId")
                        .HasColumnType("int")
                        .HasColumnName("navigationmenuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rolid");

                    b.HasKey("NavigationMenuId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("navigationmenurol", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_clientid");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_contractid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("paymentdate");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContractId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rolid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rolname");

                    b.HasKey("RoleId");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("serviceid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("servicedescription");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("servicename");

                    b.HasKey("ServiceId");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.StatusContract", b =>
                {
                    b.Property<string>("StatusId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("statusid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.HasKey("StatusId");

                    b.ToTable("statuscontract", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.Property<int>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("turnid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnId"));

                    b.Property<string>("AttentionTypeId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("attentiontype_attentiontypeid");

                    b.Property<int>("CashId")
                        .HasColumnType("int")
                        .HasColumnName("cash_cashid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("description");

                    b.Property<int>("UserGestorId")
                        .HasColumnType("int")
                        .HasColumnName("usergestorid");

                    b.HasKey("TurnId");

                    b.HasIndex("AttentionTypeId");

                    b.HasIndex("CashId");

                    b.HasIndex("UserGestorId");

                    b.ToTable("turn", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTimeOffset?>("DateApproval")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dateapproval");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deletedat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("email");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("emailhash");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("identification");

                    b.Property<string>("IdentificationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("identificationhash");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_rolid");

                    b.Property<string>("StatusId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("userstatus_statusid");

                    b.Property<int>("UserApproval")
                        .HasColumnType("int")
                        .HasColumnName("userapproval");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasFilter("[isdeleted] = 0");

                    b.HasIndex("IdentificationHash")
                        .IsUnique()
                        .HasFilter("[isdeleted] = 0");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[isdeleted] = 0");

                    b.ToTable("usertable", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserCash", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_userid");

                    b.Property<int>("CashId")
                        .HasColumnType("int")
                        .HasColumnName("cash_cashid");

                    b.HasKey("UserId", "CashId");

                    b.HasIndex("CashId");

                    b.ToTable("usercash", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserStatus", b =>
                {
                    b.Property<string>("StatusId")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("statusid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("description");

                    b.HasKey("StatusId");

                    b.ToTable("userstatus", (string)null);
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Attention", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.AttentionType", "AttentionType")
                        .WithMany("Attentions")
                        .HasForeignKey("AttentionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.User", "CashierUser")
                        .WithMany("CashierAttentions")
                        .HasForeignKey("CashierUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Attentions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Contract", "Contract")
                        .WithMany("Attentions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Viamatica.Domain.Entities.AttentionStatus", "Status")
                        .WithMany("Attentions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Turn", "Turn")
                        .WithMany("Attentions")
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttentionType");

                    b.Navigation("CashierUser");

                    b.Navigation("Client");

                    b.Navigation("Contract");

                    b.Navigation("Status");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.CashSession", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Cash", "Cash")
                        .WithMany("Sessions")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.User", "User")
                        .WithMany("CashSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.MethodPayment", "MethodPayment")
                        .WithMany("Contracts")
                        .HasForeignKey("MethodPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Service", "Service")
                        .WithMany("Contracts")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.StatusContract", "Status")
                        .WithMany("Contracts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("MethodPayment");

                    b.Navigation("Service");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Device", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Service", "Service")
                        .WithMany("Devices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.NavigationMenu", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.NavigationMenu", "ParentNavigationMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentNavigationMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentNavigationMenu");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.NavigationMenuRole", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.NavigationMenu", "NavigationMenu")
                        .WithMany("NavigationMenuRoles")
                        .HasForeignKey("NavigationMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Role", "Role")
                        .WithMany("NavigationMenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigationMenu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.AttentionType", "AttentionType")
                        .WithMany()
                        .HasForeignKey("AttentionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.Cash", "Cash")
                        .WithMany("Turns")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.User", "UserGestor")
                        .WithMany("Turns")
                        .HasForeignKey("UserGestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttentionType");

                    b.Navigation("Cash");

                    b.Navigation("UserGestor");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.UserStatus", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserCash", b =>
                {
                    b.HasOne("Viamatica.Domain.Entities.Cash", "Cash")
                        .WithMany("UserCashes")
                        .HasForeignKey("CashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Viamatica.Domain.Entities.User", "User")
                        .WithMany("UserCashes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cash");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionStatus", b =>
                {
                    b.Navigation("Attentions");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.AttentionType", b =>
                {
                    b.Navigation("Attentions");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Cash", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Turns");

                    b.Navigation("UserCashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Client", b =>
                {
                    b.Navigation("Attentions");

                    b.Navigation("Contracts");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Attentions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.MethodPayment", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.NavigationMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("NavigationMenuRoles");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Role", b =>
                {
                    b.Navigation("NavigationMenuRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Service", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.StatusContract", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.Turn", b =>
                {
                    b.Navigation("Attentions");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.User", b =>
                {
                    b.Navigation("CashSessions");

                    b.Navigation("CashierAttentions");

                    b.Navigation("Turns");

                    b.Navigation("UserCashes");
                });

            modelBuilder.Entity("Viamatica.Domain.Entities.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
